const ART = [
  {"title": "Owl",
   "filename": "owl.txt",
   "credit_text": "Donovan Bake",
   "credit_url": "https://www.asciiart.eu/animals/birds-land"},
  {"title": "Earth",
   "filename": "earth.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/space/planets"},
  {"title":"Star",
    "filename":"star.txt",
   "credit_text":"hjw",
   "credit_url":"https://www.asciiart.eu/space/stars"
  },
  {"title": "rat",
   "filename": "rat.txt",
   "credit_text": "DNE",
   "credit_url": "https://www.asciiart.eu/animals/rodents/other"},
  {"title": "Einstein",
   "filename": "einstein.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/people/famous/albert-einstein"},
  {"title": "Cat",
   "filename": "CatBox.txt",
   "credit_text": "HJS",
   "credit_url": "https://www.asciiart.eu/animals/cats"},
  {"title": "Keyboard",
   "filename": "keyboard.txt",
   "credit_text": "hjw",
   "credit_url": "https://www.asciiart.eu/music/musical-instruments"},
  {"title": "Koala",
   "filename": "koala.txt",
   "credit_text": "bw",
   "credit_url": "https://www.emojicombos.com/koala"},
   {"title": "Cute Cat",
   "filename": "bk_cat.txt",
   "credit_text": "",
   "credit_url": "https://emojicombos.com/boykisser"},
  {"title": "Mushroom",
   "filename": "mushroom.txt",
   "credit_text": "itz",
   "credit_url": "https://www.asciiart.eu/plants/mushroom"},
  {"title": "Eeyore",
   "filename": "eeyore-art.txt",
   "credit_text": "jgs",
   "credit_url": "asciiart.eu/books/winnie-the-pooh"},
  {"title": "Statue of Liberty",
   "filename": "statueOfLiberty.txt",
   "credit_text": "Joan Stark",
   "credit_url": "https://www.asciiart.eu/buildings-and-places/monuments/statue-of-liberty"},
  {"title": "punch buggy",
   "filename": "punch.txt",
   "creedit text": "Igbeard",
   "credit url": "https://www.asciiart.eu/vehicles/cars"},
  {"title": "Car",
   "filename": "wynn.txt",
   "credit_text": "NA",
   "credit_url": "https://www.asciiart.eu/vehicles/cars"},
  {"title": "Dice",
   "filename": "dice.txt",
   "credit_text": "Joan G Stark",
   "credit_url": "https://www.asciiart.eu/miscellaneous/dice"},
  {"title": "Moose",
   "filename": "moose.txt",
   "credit_text": "prs",
   "credit_url": "https://www.asciiart.eu/animals/moose"},
  {"title": "Cartman",
   "filename": "cartman.txt",
   "credit_text": "Matzec",
   "credit_url": "https://www.asciiart.eu/cartoons/south-park"},
     {"title": "knicks",
   "filename": "knicks.txt",
   "credit_text": "Brian Odom",
   "credit_url": "https://www.asciiart.eu/sports-and-outdoors/nba-logos"}

];
